config/routes.rb
Rails.application.routes.draw do
  resources :hours
  resources :days
  devise_for :users
  resources :services
  resources :businesses
  resources :types
  root 'businesses#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :description, :active, :address1, :address2, :zipcode, :phone_no, :mobile_no, :email, :fax, :type_id)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :business_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :business_description %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :business_active %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_area :address1, id: :business_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_area :address2, id: :business_address2 %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.number_field :zipcode, id: :business_zipcode %>
  </div>

  <div class="field">
    <%= form.label :phone_no %>
    <%= form.number_field :phone_no, id: :business_phone_no %>
  </div>

  <div class="field">
    <%= form.label :mobile_no %>
    <%= form.number_field :mobile_no, id: :business_mobile_no %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :business_email %>
  </div>

  <div class="field">
    <%= form.label :fax %>
    <%= form.number_field :fax, id: :business_fax %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.text_field :type_id, id: :business_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Businesses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Active</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>Zipcode</th>
      <th>Phone no</th>
      <th>Mobile no</th>
      <th>Email</th>
      <th>Fax</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.description %></td>
        <td><%= business.active %></td>
        <td><%= business.address1 %></td>
        <td><%= business.address2 %></td>
        <td><%= business.zipcode %></td>
        <td><%= business.phone_no %></td>
        <td><%= business.mobile_no %></td>
        <td><%= business.email %></td>
        <td><%= business.fax %></td>
        <td><%= business.type %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @business.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @business.active %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @business.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @business.address2 %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @business.zipcode %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @business.phone_no %>
</p>

<p>
  <strong>Mobile no:</strong>
  <%= @business.mobile_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @business.email %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @business.fax %>
</p>

<p>
  <strong>Type:</strong>
  <%= @business.type %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>